name: Debug build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/debug.yml'
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux
          - name: linux-x64
            goos: linux
            goarch: amd64
          - name: linux-x86
            goos: linux
            goarch: 386
          - name: linux-arm64
            goos: linux
            goarch: arm64
          - name: linux-arm
            goos: linux
            goarch: arm
          - name: linux-mipsel
            goos: linux
            goarch: mipsle
          - name: linux-mips64el
            goos: linux
            goarch: mips64le
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: Pre Build
        run: |
          go build -v -o prebuild ./cmd/prebuild
          go build -v -o gobuild ./cmd/build
      - name: Prepare toolchains
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          OPENWRT: ${{ matrix.openwrt }}
        run: |
          ./prebuild
      - name: Shared Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          OPENWRT: ${{ matrix.openwrt }}
        run: |
          ./gobuild -v -o naive-go ./naive
      - name: Static Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          OPENWRT: ${{ matrix.openwrt }}
        run: |
          ./gobuild -v -o naive-go -tags cronet_static -trimpath -ldflags "-s -w -buildid=" ./naive
          ./build/llvm/bin/llvm-strip ./naive-go
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: naive-go-${{ matrix.name }}
          path: naive-go